#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL (Vision)
#
# @type Quadrotor Wide
#

. ${R}etc/init.d-posix/airframes/10016_iris

# EKF2: Vision position, heading and height.
param set-default EKF2_AID_MASK 24
param set-default EKF2_HGT_MODE 0
param set-default EKF2_EV_DELAY 20

# Fully autonomous SITL: do not trigger RC-loss RTL when no joystick exists.
param set-default COM_RC_IN_MODE 4
param set-default COM_RCL_EXCEPT 4

# LPE: Vision + baro
param set-default LPE_FUSION 132

# AEQ: External heading set to use vision input
param set-default ATT_EXT_HDG_M 1
