<?xml version="1.0"?>
<package format="2">
  <name>basic_room_sim</name>
  <version>0.1.0</version>
  <description>basic_room Gazebo world for car3 single-vehicle navigation testing</description>
  <maintainer email="liuhanxu@example.com">liuhanxu</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>gazebo_ros</exec_depend>

  <export>
  </export>
</package>
